apiVersion: skaffold/v1beta7
kind: Config
build:
  artifacts:
  # - image: db
  #   context: ./db/
  - image: monitor
    context: ./monitor/
  # - image: dashboard
  #   context: ./dashboard/
  - image: sidecar
    context: ./sidecar/
  - image: primary
    context: ./primary/
  # - image: handling
  #   context: ./handling/
  # - image: processing
  #   context: ./processing/
  # - image: displaying
  #   context: ./displaying/
  # - image: storing
  #   context: ./storing/
  # - image: service
  #   context: ./service/
  # - image: test
  #   context: ./test/
  # - image: concurrency
  #   context: ./concurrency/
deploy:
  kubectl:
    manifests:
    # - ./kubernetes/db/*
    - ./kubernetes/monitor*
    # - ./kubernetes/dashboard/*
    - ./kubernetes/primary/*
    # - ./kubernetes/handling/*
    # - ./kubernetes/processing/*
    # - ./kubernetes/displaying/*
    # - ./kubernetes/storing/*
    # - ./kubernetes/service/*
    # - ./kubernetes/test/*
    # - ./kubernetes/concurrency/*
