apiVersion: skaffold/v1alpha4
kind: Config
build:
  artifacts:
  - image: primary
    context: ./primary/
  - image: handling
    context: ./handling/
  - image: processing
    context: ./processing/
  - image: displaying
    context: ./displaying/
  - image: storing
    context: ./storing/
  - image: db
    context: ./storing/db/
  - image: web-app
    context: ./web-app/
deploy:
  kubectl:
    manifests:
    - ./primary/kubernetes/*
    - ./handling/kubernetes/*
    - ./processing/kubernetes/*
    - ./displaying/kubernetes/*
    - ./storing/kubernetes/*
    - ./web-app/kubernetes/*
