apiVersion: skaffold/v1alpha4
kind: Config
build:
  artifacts:
  - image: primary
    context: ./primary/
  - image: handling
    context: ./handling/
  - image: processing
    context: ./processing/
  - image: displaying
    context: ./displaying/
deploy:
  kubectl:
    manifests:
    - ./primary/kubernetes/*
    - ./handling/kubernetes/*
    - ./processing/kubernetes/*
    - ./displaying/kubernetes/*
