apiVersion: skaffold/v1alpha3
kind: Config
build:
  artifacts:
  - imageName: primary
    workspace: ./primary/
  # - imageName: gcr.io/k8s-skaffold/leeroy-app
  #   workspace: net
deploy:
  kubectl:
    manifests:
    - ./primary/kubernetes/*
    # - ./net/kubernetes/*
