apiVersion: skaffold/v1alpha4
kind: Config
build:
  artifacts:
  - image: primary
    context: ./primary/
  - image: handling
    context: ./handling/
deploy:
  kubectl:
    manifests:
    - ./primary/kubernetes/*
    - ./handling/kubernetes/*
