apiVersion: apps/v1
kind: Deployment
metadata:
  name: primary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: primary
  template:
    metadata:
      labels:
        app: primary
    spec:
      containers:
      - name: primary
        image: primary
        ports:
        - containerPort: 50001
        volumeMounts:
        - name: varlog
          mountPath: /var/log
      - name: sidecar
        image: sidecar
        ports:
        - containerPort: 9001
        volumeMounts:
        - name: fluentd-primary
          mountPath: /fluentd/etc
        - name: varlog
          mountPath: /var/log
      volumes:
      - name: fluentd-primary
        configMap:
          name: fluentd-primary
      - name: varlog
        emptyDir: {}
