apiVersion: v1
kind: Service
metadata:
  name: primary
spec:
  selector:
    app: primary
  ports:
    - name: primary
      protocol: TCP
      port: 50001
      targetPort: 50001
    - name: primary-sidecar
      protocol: TCP
      port: 9001
      targetPort: 9001
