apiVersion: v1
kind: Service
metadata:
  name: handling
spec:
  selector:
    app: handling
  ports:
    - name: handling
      protocol: TCP
      port: 50002
      targetPort: 50002
    - name: handling-sidecar
      protocol: TCP
      port: 9002
