apiVersion: apps/v1
kind: Deployment
metadata:
  name: handling
  labels:
    app: handling
spec:
  replicas: 1
  selector:
    matchLabels:
      app: handling
  template:
    metadata:
      labels:
        app: handling
    spec:
      containers:
      - name: handling
        image: handling
        ports:
        - containerPort: 50002
