apiVersion: v1
kind: Service
metadata:
  name: web_app
  labels:
    app: web_app
spec:
  clusterIP: None
  ports:
    - port: 50006
      targetPort: 50006
      protocol: TCP
      name: web_app
  selector:
    app: web_app
