apiVersion: v1
kind: Service
metadata:
  name: monitor
  labels:
    app: monitor
spec:
  clusterIP: None
  ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: monitor
  selector:
    app: monitor
