apiVersion: v1
kind: Service
metadata:
  name: gokit
  labels:
    app: gokit
spec:
  clusterIP: None
  ports:
    - name: gokit
      protocol: TCP
      port: 50009
      targetPort: 50009
  selector:
    app: gokit
