apiVersion: apps/v1
kind: Deployment
metadata:
  name: processing
  labels:
    app: processing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: processing
  template:
    metadata:
      labels:
        app: processing
    spec:
      containers:
      - name: processing
        image: processing
        ports:
        - containerPort: 50003
