apiVersion: v1
kind: Service
metadata:
  name: handling
  labels:
    app: handling
spec:
  clusterIP: None
  ports:
    - port: 50002
      targetPort: 50002
      protocol: TCP
      name: handling
  selector:
    app: handling
