# A job to scrape an endpoint of Fluentd running on localhost.
scrape_configs:
- job_name: fluentd
 scrape_interval: 5s
 target_groups:
   - targets:
       - 'localhost:24231'
 metrics_path: /metrics
