apiVersion: v1
kind: Service
metadata:
  name: handling
  labels:
    app: handling
spec:
  clusterIP: None
  ports:
    - name: handling
      protocol: TCP
      port: 50002
      targetPort: 50002
  selector:
    app: handling
