apiVersion: v1
kind: Service
metadata:
  name: storing
  labels:
    app: storing
spec:
  clusterIP: None
  ports:
    - port: 50005
      targetPort: 50005
      protocol: TCP
      name: storing
  selector:
    app: storing
