apiVersion: apps/v1
kind: Deployment
metadata:
  name: storing
  labels:
    app: storing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storing
  template:
    metadata:
      labels:
        app: storing
    spec:
      initContainers:
      - name: check-pg-isready
        image: db
        command: ['sh', '-c', 'until pg_isready -h db -p 5432; do echo waiting for database; sleep 2; done']
      containers:
      - name: storing
        image: storing
        ports:
        - containerPort: 50005
