apiVersion: v1
kind: Service
metadata:
  name: primary
  labels:
    app: primary
spec:
  clusterIP: None
  ports:
    - port: 50001
      targetPort: 50001
      protocol: TCP
      name: primary
  selector:
    app: primary
