apiVersion: v1
kind: Service
metadata:
  name: service
  labels:
    app: service
spec:
  clusterIP: None
  ports:
    - port: 50006
      targetPort: 50006
      protocol: TCP
      name: web-app
  selector:
    app: service
