apiVersion: apps/v1
kind: Deployment
metadata:
  name: primary
  labels:
    app: primary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: primary
  template:
    metadata:
      labels:
        app: primary
    spec:
      containers:
      - name: primary
        image: primary
        ports:
        - containerPort: 50001
