apiVersion: apps/v1
kind: Deployment
metadata:
  name: primary
  labels:
    app: primary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: primary
  template:
    metadata:
      labels:
        app: primary
    spec:
      containers:
      - name: primary
        image: primary
        ports:
        - containerPort: 50001
        volumeMounts:
        - name: varlog
          mountPath: /var/log
      - name: primary-sidecar-fluentd
        image: primary-sidecar-fluentd
        ports:
        - containerPort: 9001
        volumeMounts:
        - name: varlog
          mountPath: /var/log
      volumes:
      - name: varlog
        emptyDir: {}
